// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwtjzfbvixsffrxqpfuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3dGp6ZmJ2aXhzZmZyeHFwZnVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyOTQ3ODgsImV4cCI6MjA2Mjg3MDc4OH0.15sUJlhvf5Rno_RWa1isCLJg3lSCysZIHHLzycXuaNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);